language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-tools
before_script:
  - mongoimport --host $MONGO_DB_HOST --ssl -u $MONGO_DB_USER -p $MONGO_DB_PASS --authenticationDatabase $MONGO_DB_AUTH_DB --db $MONGO_DB_DATABASE --collection $MONGO_DB_COLLECTION --drop --file crtb.json