services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools
before_script:
  - sleep 15
  - mongo --version
  - sleep 15
  - mongoimport --host $MONGO_DB_HOST --ssl -u $MONGO_DB_USER -p $MONGO_DB_PASS --authenticationDatabase $MONGO_DB_AUTH_DB --db $MONGO_DB_DATABASE --collection $MONGO_DB_COLLECTION --drop --file asv.json